### ISSUE TITLE
Create pers. or dyn. VM from Template

### ISSUE THREAD

**Issue by kerstini** [FOSS-Cloud/vm-manager#13]
On a new installation, pools are created by installer but without network range. Creating a template is not possible if no network range is assigned to the template pool. This is correct. The same check should be made by copy a template to persistent or dynamic vm's, because if no network range is defined, the image will be copied correct, but no entry in LDAP will be made. The copy mask never ends.

The process should not be able to start if this happens and a error message should appear.

**Comment by bstebler** [comment]
Approved
