### ISSUE TITLE
Assigned VMs: Autostart

### ISSUE THREAD

**Issue by kerstini** [FOSS-Cloud/vm-manager#49]
If Just one VM is assigned, autostart of dyn. VMs is not working.

**Comment by bstebler** [comment]
BST will test again and inform CWI

**Comment by bstebler** [comment]
Assigned persistent VMs are starting but not dynamic VM's.
I tested it via pool-assignment and user-assignment. It does not work with dynamic VM's
Info: fc4schools is not installed.

**Comment by bstebler** [comment]
Approved
